apiVersion: v1
kind: Service
metadata:
  name: {{ include "crabcache.fullname" . }}
  labels:
    {{- include "crabcache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
    - port: {{.Values.serviceMon.port }}
      targetPort: {{ .Values.serviceMon.port }}
      protocol: {{ .Values.serviceMon.protocol}}
      name: {{ .Values.serviceMon.name }}
  selector:
    {{- include "crabcache.selectorLabels" . | nindent 4 }}
